package com.netease.edu.boot.hystrix.core.constants;/**
 * Created by hzfjd on 17/12/24.
 */

/**
 * @author hzfjd
 * @create 17/12/24
 */
public interface HystrixBeanNameContants {

    String ORIGIN_APPLICATION_NAME_CONTROLLER_RESOLVER_BEAN_NAME = "ORIGIN_APPLICATION_NAME_CONTROLLER_RESOLVER";
    String HYSTRIX_COMMAND_APPLICATION_API_CONTROLLER_ASPECT_BEAN_NAME="HYSTRIX_COMMAND_APPLICATION_API_CONTROLLER_ASPECT";
    String HYSTRIX_COMMAND_APPLICATION_FRONT_CONTROLLER_ASPECT_BEAN_NAME="HYSTRIX_COMMAND_APPLICATION_FRONT_CONTROLLER_ASPECT";
    String HYSTRIX_COMMAND_APPLICATION_DWR_ASPECT_BEAN_NAME="HYSTRIX_COMMAND_APPLICATION_DWR_ASPECT";
}
